config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'manager/dashboard', to: "managers#dashboard"
    resources :employees, only: [:index, :show, :edit, :update]
    resources :shifts
    resources :weeks, only: [:show]
    resources :weekly_payrolls, only: [:show, :create]
    resources :positions, only: [:index, :new, :edit, :create, :update]
    resources :tip_pools, only: :show
    resources :sales, except: [:show, :index]
    get '/shift/:id/sales', to: "shifts#show" #maybe instead route this to shift show when I am done
  end


  #root if authenticated
  authenticated :employee do
    root 'employees#dashboard', as: :authenticated_root
  end

  #get 'tips/show'
  resources :tips, only: [:show]
  resources :sales, only: [:create]


  get 'employees/dashboard'
  post '/clock_in/:id', to: 'shifts#create', as: "clock_in"
  patch '/clock_out/:id', to: 'shifts#clock_out', as: "clock_out"


  devise_for :employees, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}, controllers: {registrations: "employees/registrations"}
  as :employee do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    root to: "devise/sessions#new"
    #get "/admin/employee/register" => "devise/registrations#new", as: "register_employee" # custom path to login/sign_in
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  #associations
  has_many :shifts, -> { order "id DESC" }
  has_many :sales, through: :shifts #####might not need this (check employee show)########
  has_many :weekly_payrolls
  belongs_to :position
  #has_many :tip_pools, through: :shifts ###might not need this###### add it if i need it

  #devise model
  devise :database_authenticatable, :registerable, :recoverable, :trackable, :validatable

  #validations
  validates :name, presence: true
  validates :position, presence: true
  validates :wage, presence: true
  validates :email, presence: true, uniqueness: true

  #randomize the EID
  before_create :randomize_id

  #get employee's current shift. returns nil if none
  def current_shift
    #Shift.find_by_completed_and_employee_id(false, self.id)
    Shift.employees_current_shift(self)
  end

  #get the current weekly payroll. 
  def current_weekly_payroll
    WeeklyPayroll.current_weekly_payroll(self)
  end

	private
  #randomizes the EID, doing so until unique
	def randomize_id
	  begin
	    self.id = SecureRandom.random_number(99999) + 10000
	  end while Employee.where(id: self.id).exists?
	end

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  before_action :authenticate_manager
  before_action :verify_manager_password, only: [:update]

  def index
    @employees = Employee.all.order('id ASC')

  end

  def show
    #retrieves shifts, payrolls, and employee details
    @employee = Employee.find(params[:id])
    params[:time] = -7 if params[:time].nil?
    start = Time.zone.now.advance(days: params[:time].to_i).beginning_of_day
    @shifts = @employee.shifts.where("created_at > ?", start)
    @weekly_payrolls = @employee.weekly_payrolls.order("id DESC") #WeeklyPayroll.joins(:week).
    @active = params[:active]
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  #allows managers to update the details of other employees
  def update
    #authenticate admin
    @employee = Employee.find(params[:id])

    if @employee.update_attributes(update_params)
      flash[:success] = "successful update of employee"
      redirect_to admin_employee_path(@employee)
    else
      flash.now[:danger] = "employee update failed"
      render "edit"
    end
  end

  private
  #update strong params
  def update_params
    params.require(:employee).permit(:name, :wage, :position_id, :manager, :email, :password, :password_confirmation).reject{|k,v| v.blank?}
  end

  #verifys taht the password of the manager editing
  def verify_manager_password
    #verify managers password before allowing update 
    if !current_employee.valid_password?(params[:manager][:password])
      @employee = Employee.find(params[:id])
      flash.now[:danger] = "Incorrect manager password"
      render "edit"
    end
    
  end

end

app/controllers/employees/confirmations_controller.rb
class Employees::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employees/omniauth_callbacks_controller.rb
class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/passwords_controller.rb
class Employees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employees/registrations_controller.rb
class Employees::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  skip_before_action :require_no_authentication, only: [:new, :create, :cancel]
  before_action :authenticate_manager, only: [:new, :create]

  # GET /resource/sign_up
  #def new
  #  super
  #end

  # POST /resource
  def create
    password = Devise.friendly_token.first(8)
    build_resource(sign_up_params.merge(password: password, password_confirmation: password))
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        flash[:success] = "#{resource.name} successfully signed up"
        EmployeeMailer.registration_email(resource, password).deliver_now
        #set_flash_message! :notice, :signed_up
        #sign_up(resource_name, resource)
        #respond_with resource, location: after_sign_up_path_for(resource)
        redirect_to employees_dashboard_path
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource, location: new_employee_registration_path
      #render "new"
      #redirect_to new_employee_registration_path(resource)
    end
  end


  # GET /resource/edit
  #def edit
  #  super
  #end

  # PUT /resource
  def update
    ####Ensure that if current employee is not manager, they cant edit anyone but themselves######
    super
  end

  # DELETE /resource
  def destroy
    redirect_to employees_dashboard_path
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :wage, :email, :position_id, :manager]) 
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    custom = current_employee.manager? ? [:name, :wage, :email, :position_id, :manager] : [:email]
    devise_parameter_sanitizer.permit(:account_update, keys: custom)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/employees/sessions_controller.rb
class Employees::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employees/unlocks_controller.rb
class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_employee!

  def dashboard
    @employee = current_employee
    @sale = Sale.new
  end

end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
  def time_worked_string(shift)
    Time.at(shift.finished_at - shift.created_at).utc.strftime("%H:%M")
  end

=begin
  def time_worked_decimal(shift)
    seconds_worked = shift.finished_at - shift.created_at
    hours_ratio = (seconds_worked / 1.hour).round(1)
    #minutes = 
    #not finished
  end
=end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_clock_in.html.erb
<%= button_to "clock in", clock_in_path(employee_id: @employee), remote: true %>




<%if false%>

<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#smallShoes">
Click Me
</button>

<!-- The modal -->
<div class="modal fade" id="smallShoes" tabindex="-1" role="dialog" aria-labelledby="modalLabelSmall" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="modalLabelSmall">Small Shoes</h4>
      </div>

      <div class="modal-body">
        Small shoes are typically worn by people with small feet.
      </div>

    </div>
  </div>
</div>
<%end%>

app/views/employees/_current_tip.html.erb
<div class="modal fade" id="tipModal" tabindex="-1" role="dialog" aria-labelledby="modalLabelLarge" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

			<div class="modal-header">
				<h4 class="modal-title" id="modalLabelLarge">Tip for this shift</h4>
				<button id="tipModalClose" type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				
			</div>

			<div id="tipModalBody" class="modal-body">
				
			</div>

		</div>
	</div>
</div>

app/views/employees/_sales_modal.html.erb
<!-- The modal -->
<div class="modal fade" id="saleModal" tabindex="-1" role="dialog" aria-labelledby="modalLabelLarge" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

			<div class="modal-header">
				<h4 class="modal-title" id="modalLabelLarge">Enter Sale Info</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				
			</div>

			<div class="modal-body">
				<%#=form_with model: Sale.new  do |f|%>
				<%=form_for @sale, remote: true, params: {employee_id: "test"} do |f|%>

					<%= f.label :method_of_payment, "Method of Payment:" %>
					<%= f.label :method_of_payment, "Cash" %>
					<%=f.radio_button :method_of_payment, "Cash", required: true%>
					<%= f.label :method_of_payment, "Credit" %>
					<%=f.radio_button :method_of_payment, "Credit", required: true%>
					<%= f.label :method_of_payment, "Debit" %>
					<%=f.radio_button :method_of_payment, "Debit", required: true%>
					<br/>
					<%=f.label :price%>
					<%=f.number_field :price, step: :any%>
					<br/>
					<%=f.label :tip%>
					<%=f.number_field :tip, step: :any, required: true%>
					<br/>
					<input value="53476" type="hidden" name="employee_id" id="employee_id">
					<%=f.submit%>
				<%end%>
		
			</div>

		</div>
	</div>
</div>

app/views/employees/dashboard.html.erb
<% provide(:title, "Dashboard") %>


<h1>Welcome <%=@employee.name%>!</h1>
<div id="jsAlert" class="alert" role="alert"></div>

<h4 >status: <span id="status"><%=@employee.current_shift ? "Clocked In" : "Off Shift"%></span></h4>



<div class="card-deck">



	<%=render "shared/nav_card", title: "Clock In", icon_name: "sign-in", description: "Clock in to start your shift", id: "clock-in",
		link_to_path: clock_in_path(@employee), 
		link_to_params: {remote: true, method: :post, form: {id: "clockInForm"}, id: "clockInButton", disabled: !!@employee.current_shift, class: "card-link"}
	%>
	<%=render "shared/nav_card", title: "Clock Out", icon_name: "sign-out", description: "Clock out at the end of your shift", id: "clock-out",
		link_to_path: clock_out_path(@employee), 
		link_to_params:  {method: :patch, remote: true, form: {id: "clockOutForm"}, id: "clockOutButton", disabled: !@employee.current_shift, class: "card-link"}
	%>

	<%=render "shared/nav_card", title: "Sale", icon_name: "usd", description: "Enter a sale", id: "sale",
		link_to_path: "#",
		link_to_params:  {data: {toggle: "modal", target: "#saleModal"}, class: "card-link"}
	%>


</div>
<div class="card-deck">
	<%= render "shared/nav_card", title: "Get Current Tip", icon_name: "get-pocket", description: "Click to view current shift's tip total", id: "tip",
		link_to_path: tip_path(@employee),
		link_to_params: {remote: true, method: "get", form: {id: "showTipForm"}, id: "showTipButton", class: "card-link"}
	%>

	<%=render "shared/nav_card", title: "Edit Profile", icon_name: "user-circle",  description: "Click to edit profile settings", id: "edit-profile",
		link_to_path: edit_employee_registration_path(@employee),
		link_to_params: {class: "card-link"}
	%>

  	<%if current_employee.try(:manager?)%> 
		<%=render "shared/nav_card", title: "Manager dashboard", icon_name: "tachometer", description: "Click to enter Manager's Dashboard", id: "admin-dashboard",
			link_to_path: admin_manager_dashboard_path,
			link_to_params: {class: "card-link"}
		%>
	<%end%>

</div>

<%=render "sales_modal"%>

<%=render "current_tip"%>