config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'manager/dashboard', to: "managers#dashboard"
    resources :employees, only: [:index, :show, :edit, :update]
    resources :shifts
    resources :weeks, only: [:show]
    resources :weekly_payrolls, only: [:show, :create]
    resources :positions, only: [:index, :new, :edit, :create, :update]
    resources :tip_pools, only: :show
    resources :sales, except: [:show, :index]
    get '/shift/:id/sales', to: "shifts#show" #maybe instead route this to shift show when I am done
  end


  #root if authenticated
  authenticated :employee do
    root 'employees#dashboard', as: :authenticated_root
  end

  #get 'tips/show'
  resources :tips, only: [:show]
  resources :sales, only: [:create]


  get 'employees/dashboard'
  post '/clock_in/:id', to: 'shifts#create', as: "clock_in"
  patch '/clock_out/:id', to: 'shifts#clock_out', as: "clock_out"


  devise_for :employees, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}, controllers: {registrations: "employees/registrations"}
  as :employee do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    root to: "devise/sessions#new"
    #get "/admin/employee/register" => "devise/registrations#new", as: "register_employee" # custom path to login/sign_in
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
  #validations
  validates :name, presence: true
  validates_inclusion_of :associate_with_tip, in: [true, false]
  validates :solo_associated_tip_percentage, presence: true, if: :associated?
  validates :multi_associated_tip_percentage, presence: true, if: :associated?

  #converts human format to decimal
  before_save :set_percentage, if: :percentage_changed? 


  private
  def set_percentage
    if associated?
      self.solo_associated_tip_percentage = (solo_associated_tip_percentage || 0) / 100
      self.multi_associated_tip_percentage = (self.multi_associated_tip_percentage || 0) / 100
    else
      self.solo_associated_tip_percentage = nil
      self.multi_associated_tip_percentage = nil
    end
  end

  def percentage_changed?
    self.solo_associated_tip_percentage_changed? || self.multi_associated_tip_percentage_changed? 
  end

  def associated?
    self.associate_with_tip
  end
end

app/controllers/admin/positions_controller.rb
class Admin::PositionsController < ApplicationController
  before_action :authenticate_manager

  def index
    @positions = Position.all
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new(position_params)
    if @position.save
      flash[:success] = "Position successfully saved"
      redirect_to admin_positions_path
    else
      flash.now[:danger] = "Position was not created"
      render "new"
    end

  end

  def edit
    @position = Position.find(params[:id])
  end

  def update
    @position = Position.find(params[:id])
    if @position.update_attributes(position_params)
      flash[:success] = "Successfully updated the #{@position.name} position"
      redirect_to admin_positions_path
    else
      flash.now[:danger] = "Failed to update position"
      render "edit"
    end
  end

  private
  def position_params
    params.require(:position).permit(:name, :starting_wage, :solo_associated_tip_percentage, :multi_associated_tip_percentage, :location, :associate_with_tip)
  end
end

app/helpers/admin/positions_helper.rb
module Admin::PositionsHelper
  def radio_group(legend, radio_buttons)
    final = ""
    content_tag("fieldset", class: "form-group") do
      final <<"<legend>#{legend}</legend>"
      radio_buttons.each{|button| final << "<div class='form-check'><label class='form-check-label'>#{button}</label></div>"}
      final.html_safe

    end
  end
end

app/views/admin/positions/_position_form.html.erb
<%=form_for [:admin, @position] do |f|%>
<%=radio_group("legend", [f.radio_button(:associate_with_tip, "0", checked: (@position.associate_with_tip.nil? ? false : !@position.associate_with_tip), class: "form-check-input"), f.radio_button(:associate_with_tip, "1", required: true, checked: @position.associate_with_tip, class: "form-check-input")])%>
	<div class="form-group">
		<%=f.label :name%>
		<%=f.text_field :name, class: "form-control"%>
	</div>
	<div class="form-group">
		<%=f.label :starting_wage, "Starting Wage"%>
		<%=f.number_field :starting_wage, step: 0.01, required: true, class: "form-control"%> 
	</div>
	<fieldset class="form-group">
		<legend>Associate with Tips?</legend>
		<div class="form-check">
			<label class="form-check-label">
				<%=f.radio_button :associate_with_tip, "1", required: true, checked: @position.associate_with_tip, class: "form-check-input"%> True 
			</label>
		</div>
		<div class="form-check">
			<label class="form-check-label">
				<%=f.radio_button :associate_with_tip, "0", checked: (@position.associate_with_tip.nil? ? false : !@position.associate_with_tip), class: "form-check-input"%> False
			</label>
	</fieldset>
	<div class="form-group">
		<%=f.label :solo_associated_tip_percentage, "Tip percentage when only other worker"%>
		<%=f.number_field :solo_associated_tip_percentage, value: (@position.multi_associated_tip_percentage.nil? ? nil : @position.solo_associated_tip_percentage * 100), step: 0.01, class: "form-control"%>
	</div>
	<div class="form-group">
		<%=f.label :multi_associated_tip_percentage, "Tip percentage when many other workers"%>
		<%=f.number_field :multi_associated_tip_percentage, value: (@position.multi_associated_tip_percentage.nil? ? nil : @position.multi_associated_tip_percentage * 100), step: 0.01, class: "form-control"%>
	</div>
	<fieldset class="form-group">
		<legend>Location</legend>
		<div class="form-check">
			<label class="form-check-label">
				<%=f.radio_button :location, "Front of House", required: true, class: "form-check-input"%>Front of House
			</label>
		</div>
		<div class="form-check">
			<label class="form-check-label">
				<%=f.radio_button :location, "Back of House", class: "form-check-input"%>Back of House
			</label>
		</div>
	</fieldset>
	<div class="text-center">
		<%=f.submit class: "btn btn-primary"%>
	</div>

<%end%>

app/views/admin/positions/edit.html.erb
<%=render "admin/shared/form_card", title: "Edit Position", resource: @position, resource_name: "position", form_path: "position_form"%>

app/views/admin/positions/index.html.erb
<h1>Positions</h1>
<%=render "admin/shared/create_button", path: new_admin_position_path, title: "Create Position"%>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Wage</th>
			<th>Location</th>
			<th>Associated Tip Percentages<br/>(solo, multiple)</th>
			<th>Number of Employees</th>
			<th/>
		</tr>
	</thead>
	<tbody>
		<%@positions.each do |position|%>
			<tr>
				<td><%=position.name%></td>
				<td><%=number_to_currency position.starting_wage%></td>
				<td><%=position.location%></td>
				<%if position.associate_with_tip%>
					<td><%="#{number_to_percentage(position.solo_associated_tip_percentage * 100, precision: 0)}, #{number_to_percentage(position.multi_associated_tip_percentage * 100, precision: 0)}"%></td>
				<%else%>
					<td>N/A</td>
				<%end%>
				<td><%=Employee.where(position: position).count%></td>
				<td>
					<%=render "admin/shared/edit_button", path: edit_admin_position_path(position)%>
				</td>
			</tr>
		<%end%>
	</tbody>
</table>

	

app/views/admin/positions/new.html.erb
<%=render "admin/shared/form_card", title: "Create Position", resource: @position, resource_name: "position", form_path: "position_form"%>