config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'manager/dashboard', to: "managers#dashboard"
    resources :employees, only: [:index, :show, :edit, :update]
    resources :shifts
    resources :weeks, only: [:show]
    resources :weekly_payrolls, only: [:show, :create]
    resources :positions, only: [:index, :new, :edit, :create, :update]
    resources :tip_pools, only: :show
    resources :sales, except: [:show, :index]
    get '/shift/:id/sales', to: "shifts#show" #maybe instead route this to shift show when I am done
  end


  #root if authenticated
  authenticated :employee do
    root 'employees#dashboard', as: :authenticated_root
  end

  #get 'tips/show'
  resources :tips, only: [:show]
  resources :sales, only: [:create]


  get 'employees/dashboard'
  post '/clock_in/:id', to: 'shifts#create', as: "clock_in"
  patch '/clock_out/:id', to: 'shifts#clock_out', as: "clock_out"


  devise_for :employees, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}, controllers: {registrations: "employees/registrations"}
  as :employee do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    root to: "devise/sessions#new"
    #get "/admin/employee/register" => "devise/registrations#new", as: "register_employee" # custom path to login/sign_in
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/managers_controller.rb
class Admin::ManagersController < ApplicationController
  before_action :authenticate_manager

  def dashboard
    #@back_button = {display: "Main Dashboard", path: employees_dashboard_path}
  end
end

app/helpers/admin/managers_helper.rb
module Admin::ManagersHelper
end

app/views/admin/managers/dashboard.html.erb
<h1>Manager's Dashboard</h1>

<div class="card-deck">

	<%=render "shared/nav_card", title: "Weekly Payroll", icon_name: "calendar", description: "Manage Weekly Payrolls", id: "weekly-payroll",
		link_to_path: admin_week_path(Week.current), 
		link_to_params: {class: "card-link"}
	%>

	<%=render "shared/nav_card", title: "Manage Employees", icon_name: "address-card-o", description: "Create/Manage Employee Details", id: "manage-employees",
		link_to_path: admin_employees_path, 
		link_to_params: {class: "card-link"}
	%>

	<%=render "shared/nav_card", title: "Manage Positions", icon_name: "book", description: "Create/Manage Positions", id: "manage-positions",
		link_to_path: admin_positions_path, 
		link_to_params: {class: "card-link"}
	%>

</div>