config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'manager/dashboard', to: "managers#dashboard"
    resources :employees, only: [:index, :show, :edit, :update]
    resources :shifts
    resources :weeks, only: [:show]
    resources :weekly_payrolls, only: [:show, :create]
    resources :positions, only: [:index, :new, :edit, :create, :update]
    resources :tip_pools, only: :show
    resources :sales, except: [:show, :index]
    get '/shift/:id/sales', to: "shifts#show" #maybe instead route this to shift show when I am done
  end


  #root if authenticated
  authenticated :employee do
    root 'employees#dashboard', as: :authenticated_root
  end

  #get 'tips/show'
  resources :tips, only: [:show]
  resources :sales, only: [:create]


  get 'employees/dashboard'
  post '/clock_in/:id', to: 'shifts#create', as: "clock_in"
  patch '/clock_out/:id', to: 'shifts#clock_out', as: "clock_out"


  devise_for :employees, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}, controllers: {registrations: "employees/registrations"}
  as :employee do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    root to: "devise/sessions#new"
    #get "/admin/employee/register" => "devise/registrations#new", as: "register_employee" # custom path to login/sign_in
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/week.rb
class Week < ApplicationRecord
  #associations
  has_many :weekly_payrolls, -> {order "employee_id ASC"} 
  has_many :shifts, through: :weekly_payrolls #insert this, might not actually need this
  has_many :employees, through: :weekly_payrolls

  #validations
  validates :date_started, presence: true, uniqueness: true
  

  #returns the current week. If no week exists, it creates it
  def self.current
    #get the start day adn search db 
    beginning_of_week = Time.zone.now.beginning_of_week(start_day = :sunday)
    current_week = Week.find_by_date_started(beginning_of_week)

    #return it or create one if nothing is found
    current_week || Week.create_current_week!
  end

  def employees_without_payroll
    Employee.where.not(id: self.employee_ids)
  end

  private
  #Use this in task? 
  #creates current week and returns it. Raises an exception if save fails
  def self.create_current_week!
    week = Week.new(date_started: Time.zone.now.beginning_of_week(start_day = :sunday))
    week.save!
    week
  end
end

app/controllers/admin/weeks_controller.rb
class Admin::WeeksController < ApplicationController
  before_action :authenticate_manager

  def show
    #get the week and the payrolls
    @week = Week.find(params[:id])
    @employees = Employee.all
    if !params[:employee_id].nil? && !params[:employee_id].empty?
      @employee = @employees.find(params[:employee_id])
      @weekly_payrolls = @week.weekly_payrolls.where(employee: @employee.id)
    else
      @weekly_payrolls = @week.weekly_payrolls
    end

    #and the list of employees without a payroll in the week
    @employees_without_payroll = @week.employees_without_payroll
    
    respond_to do |format|
      format.html {@weeks = Week.all.order('date_started DESC')}
      format.js
    end
  end
end

app/helpers/admin/weeks_helper.rb
module Admin::WeeksHelper
end

app/views/admin/weeks/_add_payroll.html.erb
<button type="button" class="btn btn-primary add-payroll" data-toggle="modal" data-target="#payrollModal">
	Add Payroll<%=fa_icon "plus-circle", class: "fa-1x btn-icon"%>
</button>

<!-- The modal -->
<div class="modal fade" id="payrollModal" tabindex="-1" role="dialog" aria-labelledby="modalLabelLarge" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

			<div class="modal-header">
				<h4 class="modal-title" id="modalLabelLarge">Choose employee</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				
			</div>

			<div class="modal-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>EID</th>
							<th>Name</th>
							<th>Add</th>
						</tr>
					</thead>
					<tbody id="employees_without_payroll">
						<%=render "choose_employee_to_add"%>
						
					</tbody>
				</table>
		
			</div>

		</div>
	</div>
</div>

app/views/admin/weeks/_choose_employee_to_add.html.erb
<%@employees_without_payroll.each do |employee|%>
	<tr id="<%="add_#{employee.id}"%>">
		<td><%=employee.id%></td>
		<td><%=employee.name%></td>
		<td><%=link_to fa_icon("plus", class: "test fa-2x"), admin_weekly_payrolls_path(employee: employee, week: @week), remote: true, method: "post"%></td>
	</tr>
<%end%>

app/views/admin/weeks/show.html.erb
<h1>Weekly Payrolls</h1>
<div class="container-fluid">
	<div class="row">
		<div class="col-3">
			<h5>Choose Weeks</h5>
			<%=select :weeks, :select, @weeks.map{|week| ["#{week_range(week)}",week.id]}, selected: @week.id%>
		</div>
		<div class="col-4">
			<h5>Choose Employee</h5>
			<%=select :employee, :select, @employees.map{|employee| ["#{employee.id}: #{employee.name}", employee.id]}, prompt: "All Employees"%>
			<%=render "add_payroll"%>
		</div>
	</div>
</div>

<%if false%>
<script type="text/javascript">
$(function() {
    var startDate;
    var endDate;

    var selectCurrentWeek = function() {
        window.setTimeout(function () {
            $('.week-picker').find('.ui-datepicker-current-day a').addClass('ui-state-active')
        }, 1);
    }

    $('.week-picker').datepicker( {
        showOtherMonths: true,
        selectOtherMonths: true,
        onSelect: function(dateText, inst) { 
            var date = $(this).datepicker('getDate');
            startDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay());
            endDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 6);
            var dateFormat = inst.settings.dateFormat || $.datepicker._defaults.dateFormat;
            $('#startDate').text($.datepicker.formatDate( dateFormat, startDate, inst.settings ));
            $('#endDate').text($.datepicker.formatDate( dateFormat, endDate, inst.settings ));

            selectCurrentWeek();
        },
        beforeShowDay: function(date) {
            var cssClass = '';
            if(date >= startDate && date <= endDate)
                cssClass = 'ui-datepicker-current-day';
            return [true, cssClass];
        },
        onChangeMonthYear: function(year, month, inst) {
            selectCurrentWeek();
        }
    });

    $('.week-picker .ui-datepicker-calendar tr').live('mousemove', function() { $(this).find('td a').addClass('ui-state-hover'); });
    $('.week-picker .ui-datepicker-calendar tr').live('mouseleave', function() { $(this).find('td a').removeClass('ui-state-hover'); });
});
</script>
    <div class="week-picker"></div>
    <br /><br />
    <label>Week :</label> <span id="startDate"></span> - <span id="endDate"></span>
<%end%>



<%#=date_field :date_worked, :day, required: true%>

<div id="jsAlert" class="alert" role="alert"></div>



<%#week = @weekly_payrolls[0].week%>

<%=render "admin/shared/weekly_payroll_table", weekly_payrolls: @weekly_payrolls, week: @week%>

app/views/admin/weeks/show.js.erb
//show the payrolls 
$("#weekly_payrolls_table").html("<%=escape_javascript(render 'admin/shared/weekly_payroll_table', weekly_payrolls: @weekly_payrolls, week: @week)%>");
<%title = "Weekly Payrolls for #{@week.date_started.strftime("%m/%d")} - #{(@week.date_started + 6.days).strftime("%m/%d/%Y")}"%>
$("#weekly_payrolls_title").html("<%=escape_javascript(title)%>");

//add the employees without payroll to the modal
$("#employees_without_payroll").html("<%=escape_javascript(render 'choose_employee_to_add')%>");